import { ProductConfig, CreditType } from "./types";

export const PRODUCTS: Record<CreditType, ProductConfig> = {
  "micro-credit": {
    id: "micro-credit",
    minAmount: 20,
    maxAmount: 500,
    minDuration: 1,
    maxDuration: 3,
    minRate: 12,
    maxRate: 25,
    step: 10,
    icon: "flash",
    color: "#C8A96A",
  },
  consumer: {
    id: "consumer",
    minAmount: 500,
    maxAmount: 5000,
    minDuration: 3,
    maxDuration: 36,
    minRate: 6,
    maxRate: 22,
    step: 100,
    icon: "home",
    color: "#6B8E6B",
  },
  professional: {
    id: "professional",
    minAmount: 1000,
    maxAmount: 10000,
    minDuration: 3,
    maxDuration: 24,
    minRate: 6,
    maxRate: 20,
    step: 500,
    icon: "briefcase",
    color: "#4A6FA5",
  },
  student: {
    id: "student",
    minAmount: 500,
    maxAmount: 5000,
    minDuration: 6,
    maxDuration: 36,
    minRate: 6,
    maxRate: 15,
    step: 100,
    icon: "academic",
    color: "#8B5CF6",
  },
  "salary-advance": {
    id: "salary-advance",
    minAmount: 50,
    maxAmount: 1500,
    minDuration: 1,
    maxDuration: 2,
    minRate: 8,
    maxRate: 20,
    step: 50,
    icon: "calendar",
    color: "#F59E0B",
  },
  leasing: {
    id: "leasing",
    minAmount: 1000,
    maxAmount: 20000,
    minDuration: 12,
    maxDuration: 60,
    minRate: 5,
    maxRate: 14,
    step: 500,
    icon: "car",
    color: "#10B981",
  },
};

export const CREDIT_TYPE_ORDER: CreditType[] = [
  "micro-credit",
  "consumer",
  "professional",
  "student",
  "salary-advance",
  "leasing",
];

// Scoring factors for risk assessment
export const SCORING_WEIGHTS = {
  employmentStatus: {
    cdi: 100,
    cdd: 70,
    freelance: 60,
    student: 50,
    retired: 80,
    unemployed: 20,
  },
  ageRanges: {
    "18-25": 70,
    "26-35": 90,
    "36-45": 100,
    "46-55": 90,
    "56-65": 80,
    "65+": 60,
  },
  businessYears: {
    "<1": 50,
    "1-2": 70,
    "2-5": 90,
    ">5": 100,
  },
  hasGuarantor: {
    true: 100,
    false: 60,
  },
};
