/**
 * Complete list of all countries with ISO codes
 * Used for the country selector dropdown
 */

export interface CountryInfo {
  code: string;
  name: string;
  nameEn: string;
}

export const ALL_COUNTRIES: CountryInfo[] = [
  { code: "AF", name: "Afghanistan", nameEn: "Afghanistan" },
  { code: "ZA", name: "Afrique du Sud", nameEn: "South Africa" },
  { code: "AL", name: "Albanie", nameEn: "Albania" },
  { code: "DZ", name: "Algérie", nameEn: "Algeria" },
  { code: "DE", name: "Allemagne", nameEn: "Germany" },
  { code: "AD", name: "Andorre", nameEn: "Andorra" },
  { code: "AO", name: "Angola", nameEn: "Angola" },
  { code: "SA", name: "Arabie Saoudite", nameEn: "Saudi Arabia" },
  { code: "AR", name: "Argentine", nameEn: "Argentina" },
  { code: "AM", name: "Arménie", nameEn: "Armenia" },
  { code: "AU", name: "Australie", nameEn: "Australia" },
  { code: "AT", name: "Autriche", nameEn: "Austria" },
  { code: "AZ", name: "Azerbaïdjan", nameEn: "Azerbaijan" },
  { code: "BH", name: "Bahreïn", nameEn: "Bahrain" },
  { code: "BD", name: "Bangladesh", nameEn: "Bangladesh" },
  { code: "BE", name: "Belgique", nameEn: "Belgium" },
  { code: "BZ", name: "Belize", nameEn: "Belize" },
  { code: "BJ", name: "Bénin", nameEn: "Benin" },
  { code: "BT", name: "Bhoutan", nameEn: "Bhutan" },
  { code: "BY", name: "Biélorussie", nameEn: "Belarus" },
  { code: "BO", name: "Bolivie", nameEn: "Bolivia" },
  { code: "BA", name: "Bosnie-Herzégovine", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana", nameEn: "Botswana" },
  { code: "BR", name: "Brésil", nameEn: "Brazil" },
  { code: "BN", name: "Brunei", nameEn: "Brunei" },
  { code: "BG", name: "Bulgarie", nameEn: "Bulgaria" },
  { code: "BF", name: "Burkina Faso", nameEn: "Burkina Faso" },
  { code: "BI", name: "Burundi", nameEn: "Burundi" },
  { code: "KH", name: "Cambodge", nameEn: "Cambodia" },
  { code: "CM", name: "Cameroun", nameEn: "Cameroon" },
  { code: "CA", name: "Canada", nameEn: "Canada" },
  { code: "CV", name: "Cap-Vert", nameEn: "Cape Verde" },
  { code: "CF", name: "Centrafrique", nameEn: "Central African Republic" },
  { code: "CL", name: "Chili", nameEn: "Chile" },
  { code: "CN", name: "Chine", nameEn: "China" },
  { code: "CY", name: "Chypre", nameEn: "Cyprus" },
  { code: "CO", name: "Colombie", nameEn: "Colombia" },
  { code: "KM", name: "Comores", nameEn: "Comoros" },
  { code: "CG", name: "Congo", nameEn: "Congo" },
  { code: "CD", name: "Congo (RDC)", nameEn: "DR Congo" },
  { code: "KR", name: "Corée du Sud", nameEn: "South Korea" },
  { code: "KP", name: "Corée du Nord", nameEn: "North Korea" },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire", nameEn: "Ivory Coast" },
  { code: "HR", name: "Croatie", nameEn: "Croatia" },
  { code: "CU", name: "Cuba", nameEn: "Cuba" },
  { code: "DK", name: "Danemark", nameEn: "Denmark" },
  { code: "DJ", name: "Djibouti", nameEn: "Djibouti" },
  { code: "DM", name: "Dominique", nameEn: "Dominica" },
  { code: "EG", name: "Égypte", nameEn: "Egypt" },
  { code: "AE", name: "Émirats Arabes Unis", nameEn: "United Arab Emirates" },
  { code: "EC", name: "Équateur", nameEn: "Ecuador" },
  { code: "ER", name: "Érythrée", nameEn: "Eritrea" },
  { code: "ES", name: "Espagne", nameEn: "Spain" },
  { code: "EE", name: "Estonie", nameEn: "Estonia" },
  { code: "US", name: "États-Unis", nameEn: "United States" },
  { code: "ET", name: "Éthiopie", nameEn: "Ethiopia" },
  { code: "FJ", name: "Fidji", nameEn: "Fiji" },
  { code: "FI", name: "Finlande", nameEn: "Finland" },
  { code: "FR", name: "France", nameEn: "France" },
  { code: "GA", name: "Gabon", nameEn: "Gabon" },
  { code: "GM", name: "Gambie", nameEn: "Gambia" },
  { code: "GE", name: "Géorgie", nameEn: "Georgia" },
  { code: "GH", name: "Ghana", nameEn: "Ghana" },
  { code: "GR", name: "Grèce", nameEn: "Greece" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala" },
  { code: "GN", name: "Guinée", nameEn: "Guinea" },
  { code: "GW", name: "Guinée-Bissau", nameEn: "Guinea-Bissau" },
  { code: "GQ", name: "Guinée Équatoriale", nameEn: "Equatorial Guinea" },
  { code: "GY", name: "Guyana", nameEn: "Guyana" },
  { code: "HT", name: "Haïti", nameEn: "Haiti" },
  { code: "HN", name: "Honduras", nameEn: "Honduras" },
  { code: "HK", name: "Hong Kong", nameEn: "Hong Kong" },
  { code: "HU", name: "Hongrie", nameEn: "Hungary" },
  { code: "IN", name: "Inde", nameEn: "India" },
  { code: "ID", name: "Indonésie", nameEn: "Indonesia" },
  { code: "IQ", name: "Irak", nameEn: "Iraq" },
  { code: "IR", name: "Iran", nameEn: "Iran" },
  { code: "IE", name: "Irlande", nameEn: "Ireland" },
  { code: "IS", name: "Islande", nameEn: "Iceland" },
  { code: "IL", name: "Israël", nameEn: "Israel" },
  { code: "IT", name: "Italie", nameEn: "Italy" },
  { code: "JM", name: "Jamaïque", nameEn: "Jamaica" },
  { code: "JP", name: "Japon", nameEn: "Japan" },
  { code: "JO", name: "Jordanie", nameEn: "Jordan" },
  { code: "KZ", name: "Kazakhstan", nameEn: "Kazakhstan" },
  { code: "KE", name: "Kenya", nameEn: "Kenya" },
  { code: "KG", name: "Kirghizistan", nameEn: "Kyrgyzstan" },
  { code: "KW", name: "Koweït", nameEn: "Kuwait" },
  { code: "LA", name: "Laos", nameEn: "Laos" },
  { code: "LS", name: "Lesotho", nameEn: "Lesotho" },
  { code: "LV", name: "Lettonie", nameEn: "Latvia" },
  { code: "LB", name: "Liban", nameEn: "Lebanon" },
  { code: "LR", name: "Liberia", nameEn: "Liberia" },
  { code: "LY", name: "Libye", nameEn: "Libya" },
  { code: "LI", name: "Liechtenstein", nameEn: "Liechtenstein" },
  { code: "LT", name: "Lituanie", nameEn: "Lithuania" },
  { code: "LU", name: "Luxembourg", nameEn: "Luxembourg" },
  { code: "MK", name: "Macédoine du Nord", nameEn: "North Macedonia" },
  { code: "MG", name: "Madagascar", nameEn: "Madagascar" },
  { code: "MY", name: "Malaisie", nameEn: "Malaysia" },
  { code: "MW", name: "Malawi", nameEn: "Malawi" },
  { code: "MV", name: "Maldives", nameEn: "Maldives" },
  { code: "ML", name: "Mali", nameEn: "Mali" },
  { code: "MT", name: "Malte", nameEn: "Malta" },
  { code: "MA", name: "Maroc", nameEn: "Morocco" },
  { code: "MU", name: "Maurice", nameEn: "Mauritius" },
  { code: "MR", name: "Mauritanie", nameEn: "Mauritania" },
  { code: "MX", name: "Mexique", nameEn: "Mexico" },
  { code: "MD", name: "Moldavie", nameEn: "Moldova" },
  { code: "MC", name: "Monaco", nameEn: "Monaco" },
  { code: "MN", name: "Mongolie", nameEn: "Mongolia" },
  { code: "ME", name: "Monténégro", nameEn: "Montenegro" },
  { code: "MZ", name: "Mozambique", nameEn: "Mozambique" },
  { code: "MM", name: "Myanmar", nameEn: "Myanmar" },
  { code: "NA", name: "Namibie", nameEn: "Namibia" },
  { code: "NP", name: "Népal", nameEn: "Nepal" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua" },
  { code: "NE", name: "Niger", nameEn: "Niger" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria" },
  { code: "NO", name: "Norvège", nameEn: "Norway" },
  { code: "NZ", name: "Nouvelle-Zélande", nameEn: "New Zealand" },
  { code: "OM", name: "Oman", nameEn: "Oman" },
  { code: "UG", name: "Ouganda", nameEn: "Uganda" },
  { code: "UZ", name: "Ouzbékistan", nameEn: "Uzbekistan" },
  { code: "PK", name: "Pakistan", nameEn: "Pakistan" },
  { code: "PA", name: "Panama", nameEn: "Panama" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", nameEn: "Papua New Guinea" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay" },
  { code: "NL", name: "Pays-Bas", nameEn: "Netherlands" },
  { code: "PE", name: "Pérou", nameEn: "Peru" },
  { code: "PH", name: "Philippines", nameEn: "Philippines" },
  { code: "PL", name: "Pologne", nameEn: "Poland" },
  { code: "PT", name: "Portugal", nameEn: "Portugal" },
  { code: "QA", name: "Qatar", nameEn: "Qatar" },
  { code: "DO", name: "République Dominicaine", nameEn: "Dominican Republic" },
  { code: "CZ", name: "République Tchèque", nameEn: "Czech Republic" },
  { code: "RO", name: "Roumanie", nameEn: "Romania" },
  { code: "GB", name: "Royaume-Uni", nameEn: "United Kingdom" },
  { code: "RU", name: "Russie", nameEn: "Russia" },
  { code: "RW", name: "Rwanda", nameEn: "Rwanda" },
  { code: "SN", name: "Sénégal", nameEn: "Senegal" },
  { code: "RS", name: "Serbie", nameEn: "Serbia" },
  { code: "SL", name: "Sierra Leone", nameEn: "Sierra Leone" },
  { code: "SG", name: "Singapour", nameEn: "Singapore" },
  { code: "SK", name: "Slovaquie", nameEn: "Slovakia" },
  { code: "SI", name: "Slovénie", nameEn: "Slovenia" },
  { code: "SO", name: "Somalie", nameEn: "Somalia" },
  { code: "SD", name: "Soudan", nameEn: "Sudan" },
  { code: "SS", name: "Soudan du Sud", nameEn: "South Sudan" },
  { code: "LK", name: "Sri Lanka", nameEn: "Sri Lanka" },
  { code: "SE", name: "Suède", nameEn: "Sweden" },
  { code: "CH", name: "Suisse", nameEn: "Switzerland" },
  { code: "SR", name: "Suriname", nameEn: "Suriname" },
  { code: "SZ", name: "Eswatini", nameEn: "Eswatini" },
  { code: "SY", name: "Syrie", nameEn: "Syria" },
  { code: "TJ", name: "Tadjikistan", nameEn: "Tajikistan" },
  { code: "TZ", name: "Tanzanie", nameEn: "Tanzania" },
  { code: "TD", name: "Tchad", nameEn: "Chad" },
  { code: "TH", name: "Thaïlande", nameEn: "Thailand" },
  { code: "TL", name: "Timor Oriental", nameEn: "East Timor" },
  { code: "TG", name: "Togo", nameEn: "Togo" },
  { code: "TN", name: "Tunisie", nameEn: "Tunisia" },
  { code: "TM", name: "Turkménistan", nameEn: "Turkmenistan" },
  { code: "TR", name: "Turquie", nameEn: "Turkey" },
  { code: "UA", name: "Ukraine", nameEn: "Ukraine" },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay" },
  { code: "VU", name: "Vanuatu", nameEn: "Vanuatu" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam" },
  { code: "YE", name: "Yémen", nameEn: "Yemen" },
  { code: "ZM", name: "Zambie", nameEn: "Zambia" },
  { code: "ZW", name: "Zimbabwe", nameEn: "Zimbabwe" },
];

// Countries with specific configurations (personalized experience)
export const CONFIGURED_COUNTRIES = ["FR", "BE", "CH", "ES"];

// Check if a country has specific configuration
export function hasCountryConfig(code: string): boolean {
  return CONFIGURED_COUNTRIES.includes(code);
}

// Get country name by code and locale
export function getCountryName(code: string, locale: string = "fr"): string {
  const country = ALL_COUNTRIES.find((c) => c.code === code);
  if (!country) return code;
  return locale === "fr" ? country.name : country.nameEn;
}
